-- File: toplevel.vhd
-- Generated by MyHDL 0.11.42
-- Date: Thu Mar 12 18:10:34 2026


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_01142.all;

entity toplevel is
    port (
        LEDR: out unsigned(9 downto 0);
        SW: in unsigned(9 downto 0);
        KEY: in unsigned(3 downto 0);
        HEX0: out unsigned(6 downto 0);
        HEX1: in unsigned(6 downto 0);
        HEX2: in unsigned(6 downto 0);
        HEX3: in unsigned(6 downto 0);
        HEX4: in unsigned(6 downto 0);
        HEX5: in unsigned(6 downto 0);
        CLOCK_50: in std_logic;
        RESET_N: in std_logic
    );
end entity toplevel;


architecture MyHDL of toplevel is



signal bin2hex0_value: unsigned(3 downto 0);
type t_array_ledr_s is array(0 to 10-1) of std_logic;
signal ledr_s: t_array_ledr_s;
type t_array_adder0_c is array(0 to 4-1) of std_logic;
signal adder0_c: t_array_adder0_c;
type t_array_adder0_fullAdder0_s is array(0 to 3-1) of std_logic;
signal adder0_fullAdder0_s: t_array_adder0_fullAdder0_s;
type t_array_adder0_fullAdder1_s is array(0 to 3-1) of std_logic;
signal adder0_fullAdder1_s: t_array_adder0_fullAdder1_s;
type t_array_adder0_fullAdder2_s is array(0 to 3-1) of std_logic;
signal adder0_fullAdder2_s: t_array_adder0_fullAdder2_s;
type t_array_adder0_fullAdder3_s is array(0 to 3-1) of std_logic;
signal adder0_fullAdder3_s: t_array_adder0_fullAdder3_s;

begin



bin2hex0_value(3) <= ledr_s(3);
bin2hex0_value(2) <= ledr_s(2);
bin2hex0_value(1) <= ledr_s(1);
bin2hex0_value(0) <= ledr_s(0);


adder0_fullAdder0_s(0) <= (SW(0) xor SW(6));
adder0_fullAdder0_s(1) <= (SW(0) and SW(6));


ledr_s(0) <= ('0' xor adder0_fullAdder0_s(0));
adder0_fullAdder0_s(2) <= ('0' and adder0_fullAdder0_s(0));


adder0_c(0) <= (adder0_fullAdder0_s(1) or adder0_fullAdder0_s(2));


adder0_fullAdder1_s(0) <= (SW(1) xor SW(7));
adder0_fullAdder1_s(1) <= (SW(1) and SW(7));


ledr_s(1) <= (adder0_c(0) xor adder0_fullAdder1_s(0));
adder0_fullAdder1_s(2) <= (adder0_c(0) and adder0_fullAdder1_s(0));


adder0_c(1) <= (adder0_fullAdder1_s(1) or adder0_fullAdder1_s(2));


adder0_fullAdder2_s(0) <= (SW(2) xor SW(8));
adder0_fullAdder2_s(1) <= (SW(2) and SW(8));


ledr_s(2) <= (adder0_c(1) xor adder0_fullAdder2_s(0));
adder0_fullAdder2_s(2) <= (adder0_c(1) and adder0_fullAdder2_s(0));


adder0_c(2) <= (adder0_fullAdder2_s(1) or adder0_fullAdder2_s(2));


adder0_fullAdder3_s(0) <= (SW(3) xor SW(9));
adder0_fullAdder3_s(1) <= (SW(3) and SW(9));


ledr_s(3) <= (adder0_c(2) xor adder0_fullAdder3_s(0));
adder0_fullAdder3_s(2) <= (adder0_c(2) and adder0_fullAdder3_s(0));


adder0_c(3) <= (adder0_fullAdder3_s(1) or adder0_fullAdder3_s(2));


ledr_s(9) <= adder0_c((4 - 1));

TOPLEVEL_BIN2HEX0_COMB: process (bin2hex0_value) is
    variable v: integer;
begin
    v := to_integer(bin2hex0_value);
    if (v = 0) then
        HEX0 <= to_unsigned(64, 7);
    else
        case v is
            when 0 =>
                HEX0 <= to_unsigned(121, 7);
            when 1 =>
                HEX0 <= to_unsigned(36, 7);
            when 2 =>
                HEX0 <= to_unsigned(48, 7);
            when 3 =>
                HEX0 <= to_unsigned(25, 7);
            when 4 =>
                HEX0 <= to_unsigned(18, 7);
            when 5 =>
                HEX0 <= to_unsigned(2, 7);
            when 6 =>
                HEX0 <= to_unsigned(120, 7);
            when 7 =>
                HEX0 <= to_unsigned(0, 7);
            when 8 =>
                HEX0 <= to_unsigned(16, 7);
            when 9 =>
                HEX0 <= to_unsigned(8, 7);
            when 10 =>
                HEX0 <= to_unsigned(3, 7);
            when 11 =>
                HEX0 <= to_unsigned(70, 7);
            when 12 =>
                HEX0 <= to_unsigned(33, 7);
            when 13 =>
                HEX0 <= to_unsigned(6, 7);
            when 14 =>
                HEX0 <= to_unsigned(14, 7);
            when others =>
                HEX0 <= to_unsigned(127, 7);
        end case;
    end if;
end process TOPLEVEL_BIN2HEX0_COMB;

TOPLEVEL_COMB: process (ledr_s) is
begin
    for i in 0 to 10-1 loop
        LEDR(i) <= ledr_s(i);
    end loop;
end process TOPLEVEL_COMB;

end architecture MyHDL;
